version: '3'

services:
  app:
    build: .
    container_name: py-test-fastapi
    ports:
      -"8000:000"
    
    command: bash -c "uvicorn app.main:app"
    env_file:
      - .env
    volumes:
      - ./fastapi_app.db:/app/fastapi_app.db:delegated
